import type { Metadata } from 'next';
import Navbar from '@/components/navbar/Navbar';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import Html from '@/shared/layouts/Html';
import { THasChildren } from '@/types';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = THasChildren;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <Html>
      <ReactQueryProvider>
        <Navbar />
        {children}
      </ReactQueryProvider>
    </Html>
  );
}
