import type { Metadata } from 'next';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import Html from '@/shared/layouts/Html';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  return (
    <Html>
      <ReactQueryProvider>
        <p>Hi</p>
      </ReactQueryProvider>
    </Html>
  );
}
